FROM ruby:3.2.0

ENV LANG C.UFT-8
ENV TZ Asia/Tokyo
ENV RAILS_ENV=development

RUN apt-get update -qq && apt-get install -y \
  ca-certificates curl gnupg default-mysql-client vim nano

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install

COPY . .

CMD ["bin/dev"]